### PR TITLE
allow compilation time checks

### PR DESCRIPTION
**Pull request by MuhammadAnnaqeeb**
use format_args!() macro to allow compile time checks. Now code like:
```
let a: i32;
let b: &mut u8 = &mut 5;
scan!("{}, {}{", a, *b);
```
will not pass compilation, however code as
```
let a: i32;
let b: &mut u8 = &mut 5;
scan!("{:o}, {:o}", a, *b);
```
 will pass compilation and fail at runtime

### CODE REVIEW

**Comment by oli-obk** [comment]
Cool! could you add a test please?

You can simply add another line to https://github.com/oli-obk/rust-si/blob/master/tests/tuple.rs together with a new file that contains your examples (don't put them in the `examples` folder, make a new `failing-examples` folder) and make the test a `#[should_panic]` test.

**Comment by MuhammadAnnaqeeb** [comment]
Here it is. I added the test in this commit: https://github.com/MuhammadAnnaqeeb/rust-si/commit/fe2b3b6d436bf02127d2ff37857083a3f98acf15 , and its build log on Travis CI is at: https://travis-ci.org/MuhammadAnnaqeeb/rust-si/builds/178998569

**Comment by oli-obk** [comment]
Thanks. I took the liberty of modifying your master branch through the new github feature that allow s maintainers to modify prs.

**Comment by MuhammadAnnaqeeb** [comment]
You are welcome. Thank you.

**Pull request merged**
